SET SERVEROUTPUT ON;
SHOW SERVEROUTPUT;


CREATE OR REPLACE FUNCTION FACTORIAL(N INT)RETURN INT AS FACT INT;
BEGIN
FACT:=1;
FOR I IN 1..N LOOP
FACT:=FACT*I;
END LOOP;
RETURN FACT;
END;
/
DECLARE
NUM INTEGER;
RESULT INTEGER;
BEGIN
NUM:=&NUM;
RESULT:=FACTORIAL(NUM);
DBMS_OUTPUT.PUT_LINE('Factorial is '||RESULT);
END;
/
CREATE OR REPLACE FUNCTION TOTAL_CUSTONERS RETURN NUMBER IS TOTAL 
NUMBER(2):=0;
BEGIN
SELECT COUNT(*) INTO TOTAL FROM CUSTOMERS_CSEA_52;
RETURN TOTAL;
END;
/
DECLARE
NUM NUMBER(2);
BEGIN
NUM:=TOTAL_CUSTONERS();
DBMS_OUTPUT.PUT_LINE('Total no. of customers='||num);
END;
/







CREATE TABLE SUTUDENT_DETAILS_CSEA_52(ROLL_NO INT,MARKS INT,PHONE_NO INT,PRIMARY KEY(ROLL_NO));
DESC SUTUDENT_DETAILS_CSEA_52;
INSERT INTO SUTUDENT_DETAILS_CSEA_52 VALUES(1,32,9867543212);
INSERT INTO SUTUDENT_DETAILS_CSEA_52 VALUES(2,29,9934213212);
INSERT INTO SUTUDENT_DETAILS_CSEA_52 VALUES(3,40,9889654321);
INSERT INTO SUTUDENT_DETAILS_CSEA_52 VALUES(4,30,9723451210);
INSERT INTO SUTUDENT_DETAILS_CSEA_52 VALUES(5,25,9076532112);
SELECT * FROM SUTUDENT_DETAILS_CSEA_52;
CREATE OR REPLACE PROCEDURE PR1 AS 
BEGIN 
UPDATE SUTUDENT_DETAILS_CSEA_52 SET MARKS=MARKS+(MARKS*0.05);
END;
/
BEGIN
PR1;
END;
/
SELECT * FROM SUTUDENT_DETAILS_CSEA_52;







CREATE TABLE CUSTOMER_DETAILS_CSEA_52(CUST_ID INT UNIQUE,CUST_NAME VARCHAR(15),ADDRESS VARCHAR(30));
DESC CUSTOMER_DETAILS_CSEA_52;
CREATE OR REPLACE TRIGGER TRIGGER1 AFTER INSERT ON CUSTOMER_DETAILS_CSEA_52 FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('The row is inserted');
END;
/
INSERT INTO CUSTOMER_DETAILS_CSEA_52 VALUES(100,'Raj K.S','Sardar Colony');
SELECT * FROM CUSTOMER_DETAILS_CSEA_52;
CREATE TABLE EMP_DETAILS_CSEA_52(EMPID INT UNIQUE,EMPNAME VARCHAR(15),SALARY INT);
DESC EMP_DETAILS_CSEA_52;
CREATE OR REPLACE TRIGGER TRIGGER2 AFTER INSERT OR UPDATE ON EMP_DETAILS_CSEA_52 FOR EACH ROW WHEN(NEW.SALARY>20000)
BEGIN
DBMS_OUTPUT.PUT_LINE('Salary value>20000');
END;
/
INSERT INTO EMP_DETAILS_CSEA_52 VALUES(200,'James Varghese',10000);
INSERT INTO EMP_DETAILS_CSEA_52 VALUES(201,'ALICE JOHN',30000);
SELECT * FROM EMP_DETAILS_CSEA_52;
UPDATE EMP_DETAILS_CSEA_52 SET SALARY=50000 WHERE EMPID=201;
SELECT * FROM EMP_DETAILS_CSEA_52;
CREATE TABLE CUST_COUNT_CSEA_52(COUNT_ROW INT);
DESC CUST_COUNT_CSEA_52;
INSERT INTO CUST_COUNT_CSEA_52 VALUES(0);
SELECT * FROM CUST_COUNT_CSEA_52;
CREATE OR REPLACE TRIGGER TRIGGER3 BEFORE INSERT OR DELETE ON CUSTOMER_DETAILS_CSEA_52 FOR EACH ROW
BEGIN
IF DELETING THEN
UPDATE CUST_COUNT_CSEA_52 SET COUNT_ROW=COUNT_ROW-1;
ELSE
UPDATE CUST_COUNT_CSEA_52 SET COUNT_ROW=COUNT_ROW+1;
END IF;
END;
/
INSERT INTO CUSTOMER_DETAILS_CSEA_52 VALUES(104,'Nikit Johns','SM St.');
INSERT INTO CUSTOMER_DETAILS_CSEA_52 VALUES(105,'Jacob Reji','Manthil(H)');
SELECT * FROM CUSTOMER_DETAILS_CSEA_52;
SELECT * FROM CUST_COUNT_CSEA_52;
DELETE FROM CUSTOMER_DETAILS_CSEA_52 WHERE CUST_ID=104;
SELECT * FROM CUSTOMER_DETAILS_CSEA_52;
SELECT * FROM CUST_COUNT_CSEA_52;
CREATE TABLE DELETED_CSEA_52(EMPID INT UNIQUE,EMPNAME VARCHAR(15),SALARY INT);
DESC DELETED_CSEA_52;
CREATE TABLE UPDATED_CSEA_52(EMPID INT UNIQUE,EMPNAME VARCHAR(15),SALARY INT);
DESC UPDATED_CSEA_52;
CREATE OR REPLACE TRIGGER TRIGGER4 AFTER DELETE OR UPDATE ON EMP_DETAILS_CSEA_52 FOR EACH ROW
BEGIN
IF DELETING THEN
INSERT INTO DELETED_CSEA_52 VALUES(:OLD.EMPID,:OLD.EMPNAME,:OLD.SALARY);
ELSE
INSERT INTO UPDATED_CSEA_52 VALUES(:NEW.EMPID,:NEW.EMPNAME,:NEW.SALARY);
END IF;
END;
/
UPDATE EMP_DETAILS_CSEA_52 SET EMPNAME='Ben John' WHERE EMPID=201;
SELECT * FROM EMP_DETAILS_CSEA_52;
SELECT * FROM UPDATED_CSEA_52;
DELETE FROM EMP_DETAILS_CSEA_52 WHERE EMPID=201;
SELECT * FROM EMP_DETAILS_CSEA_52;
SELECT * FROM DELETED_CSEA_52;
COMMIT;
