SELECT CEIL(52.29) FROM DUAL;
SELECT CEIL(-52.9) FROM DUAL;
SELECT CEIL(52/3) FROM DUAL;
SELECT FLOOR(52.76) FROM DUAL;
SELECT FLOOR(-52.3) FROM DUAL;
SELECT FLOOR(52/4) FROM DUAL;
SELECT SQRT(52) FROM DUAL;
SELECT SQRT(2) FROM DUAL;
SELECT ABS(52.29) FROM DUAL;
SELECT ABS(-52.14) FROM DUAL;
SELECT ABS(-52) FROM DUAL;
SELECT SYSDATE AS NOW FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DD:MM:YYYY')AS DATE_FORMAT,TO_CHAR(SYSDATE,'HH:MI:SS')AS TIME_FORMAT FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT LEAST('Hi','Hello','Praveen') FROM DUAL;
SELECT GREATEST('Hi','Hello','Praveen') FROM DUAL;
SELECT LTRIM('  Trim me') FROM DUAL;
SELECT RTRIM('I love India       ') FROM DUAL;
SELECT RPAD('Praveen',15,'X') FROM DUAL;
SELECT RPAD(123,6,'0') FROM DUAL;
SELECT REVERSE('uoy era woh olleh') FROM DUAL;
SELECT TO_CHAR('palindrome') FROM DUAL WHERE 'racecar'=REVERSE('racecar');
SELECT LENGTH('Oracle Database') FROM DUAL;
SELECT CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('Oracle',' '),'SQL'),' '),'is'),' '),'powerful'),' '),'and'),' '),'flexible') FROM DUAL;
SELECT CONCAT(CONCAT('Praveen',' '),'Rajan') FROM DUAL;
SELECT SUBSTR('India is my country',6,3) FROM DUAL;
SELECT SUBSTR('Praveen',LENGTH('Praveen')/2,3) FROM DUAL;
SELECT SUBSTR('Substring',1,3) FROM DUAL;
COMMIT;




